### PR TITLE
Update CSI_localization.fr_fr.conf

### PR DESCRIPTION
**Pull request by pokertour**
Add french translation

### CODE REVIEW

**Comment by Pi123263** [comment]
Did you use the string editor in the workbench to add the strings to the stringtable or just manually add them to the conf file?
Because they're not showing up in the string editor for me
If you're not sure how to use the string editor let me know and I can do it for you

**Comment by pokertour** [comment]
manually directly on github, do you want me to do it with string editor ?

**Comment by Pi123263** [comment]
Yes, I dont think it works correctly if its not done in the string editor but I'm not sure so would be best to do it through that
As mentioned if you need help feel free to ask 👍

**Comment by Pi123263** [comment]
Thank you already for the translations though <3

**Comment by tanaaKa** [comment]
Some documentation as well, if it helps:
https://community.bistudio.com/wiki/Arma_Reforger:Mod_Localisation

**Comment by Pi123263** [comment]
I went ahead and added the strings to the central stringtable, fyi @Njpatman

**Comment by Njpatman** [comment]
Integrated in 1.5.4

**Pull request closed without merging**
